### ISSUE TITLE
z-index of icons

### ISSUE THREAD

**Issue by JohnCashmore** [scottdejonge/map-icons#13]
IS there anyway to join the zindex of the marker and the label or perhaps pass it in as a option to stop this sort of thing happening?

![image](https://cloud.githubusercontent.com/assets/2050794/3215156/d73f29b6-efbb-11e3-9e4b-8f5a1a5c3c97.png)

**Comment by tanelkarp** [comment]
Sorry, but I don't see this issue solved either. Using Chrome, this is what I see on http://map-icons.com/demo.html
![image](https://cloud.githubusercontent.com/assets/2767873/6152340/09f7bb30-b225-11e4-827e-daa41f556209.png)

**Comment by JohnnyTMD** [comment]
I have same problem.  (
