### ISSUE TITLE
Small Typo on the Webseite

### ISSUE THREAD

**Issue by MarkPochert** [scottdejonge/map-icons#17]
Markers
=> var MAP-PIN (With normal -)

In the Example
icon: {
		path: MAP_PIN, (with underscore)
		fillColor: '#0E77E9',
		fillOpacity: 1,
		strokeColor: '',
		strokeWeight: 0,
		scale: 1/2
	}

**Comment by scottdejonge** [comment]
Fixed in v3.0.0
