### ISSUE TITLE
map-icon-gym

### ISSUE THREAD

**Issue by alphanso** [scottdejonge/map-icons#19]
Hi,

Thanks for this awesome work. 

I see some noticeable difference in icons in chrome and firefox. I only care about gym icon. Dumb bells have lines in chrome but they are not visible in firefox.
I am using Mac book Pro.

Thanks
Rishabh

**Comment by scottdejonge** [comment]
This is most likely an issue with text rendering in Firefox and the gym asset not being rendered subpixel like Chrome.
