### ISSUE TITLE
Register library with Bower

### ISSUE THREAD

**Issue by knownasilya** [scottdejonge/map-icons#2]
[Bower](http://bower.io/) is a client-side package manager, and Map-Icons should be in their repository :)

See [how to register](http://bower.io/#registering-packages).

**Comment by dabos-GFI** [comment]
You can use bower with the following command :
```sh
    $ bower install scottdejonge/Map-Icons --save
```

If you want a specific version, you can reference a tag/release using

```sh
    $ bower install scottdejonge/Map-Icons#2.1.0 --save
```

Regards,

Damien

**Comment by c9dd** [comment]
I maybe be wrong (I'm new to bower) but it looks like the bower file is missing 'main'.

**Comment by knownasilya** [comment]
If not bower, then npm would be great.

**Comment by aristidesfl** [comment]
```
$bower search map-icons
Search results:

    map-icons https://github.com/scottdejonge/Map-Icons.git
```
