### ISSUE TITLE
Create releases for versions

### ISSUE THREAD

**Issue by dabos-GFI** [scottdejonge/Map-Icons#20]
Hi Scott,

You made a great job.
It would be nice to create releases to be able to track stable versions and use some package managers like npm, bower or component.
https://help.github.com/articles/creating-releases/
Just add a tag, i.e. 2.1.0 (using semantic versioning)
then package managers will be able to use a short name like 'scottdejonge/Map-Icons#2.1.0' to refer a specific release.
Thanks a lot :)

Best regards,

Damien Abos

**Comment by scottdejonge** [comment]
Done.
