### ISSUE TITLE
Marker animation works incorrectly

### ISSUE THREAD

**Issue by skhvan1111** [scottdejonge/map-icons#24]
When I`m trying to add  google.maps.Animation.BOUNCE animation to marker,  marker background starts bouncing as expected but without icon.
Does someone have experience with that issue?
Thanks!

**Comment by scottdejonge** [comment]
Icon label is pined to marker location sitting absolute above the map canvas, rather than being drawn onto the marker itself. Sucks I know. I don't have a workaround at this time.
