### ISSUE TITLE
map-icons.com suspended

### ISSUE THREAD

**Issue by ksavenkov** [scottdejonge/Map-Icons#29]
Not quite a code issue, but the website seems to be suspended by the hoster.
![screen shot 2015-08-07 at 22 33 38](https://cloud.githubusercontent.com/assets/1893114/9144255/6b184b18-3d54-11e5-890f-8c1841910246.png)

**Comment by DevinWalker** [comment]
Yup I saw that too +1

**Comment by soulcreate** [comment]
+1

**Comment by scottdejonge** [comment]
You should be able to view the docs here for now: http://scottdejonge.github.io/Map-Icons/

**Comment by DevinWalker** [comment]
Cool - looks like the library needs to be updated on the demo site though... notice the "<"

**Comment by scottdejonge** [comment]
@DevinWalker I've updated the links in README.md
