### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by c9dd** [scottdejonge/map-icons#30]
Hi

I'm getting this error message

Uncaught ReferenceError: google is not defined
(anonymous function) @ map-icons.js:42

**Comment by scottdejonge** [comment]
Have you included the Google Maps API before map-icons.js?

**Comment by c9dd** [comment]
Perhaps. I will take a look

**Comment by RaviRamDhali** [comment]
I am getting the same error.  I have the scripts in the following orders:

**Uncaught ReferenceError: google is not defined(anonymous function) @ map-icons.js:42**

```
<script async defer src="https://maps.googleapis.com/maps/api/js?key=***********&callback=initMap">
    </script>

    <script src="js/map-icons.js"></script>

```

**Comment by otr-tomek** [comment]
+1 for async

**Comment by cruelmelody** [comment]
Yep. Same error. Does this work with async? Has anyone found a workaround?
