### ISSUE TITLE
Circle Pin

### ISSUE THREAD

**Issue by tiarebalbi** [scottdejonge/map-icons#41]
Thank you for your current work, it's great!

I was wondering if would be possible integration a circle into the list of Pins ?

**Comment by scottdejonge** [comment]
You an easily create a circle using [SVG Path notation](http://www.w3.org/TR/SVG/paths.html#PathData) and include that instead of one of the predefined shapes as markers. They are included as examples and simple shapes for markers, users can easily add on top.
