### ISSUE TITLE
Any Library to use it in iphone app

### ISSUE THREAD

**Issue by manoj529** [scottdejonge/map-icons#48]
I'm working on a ios APP where i need to put similar icons. Do you have any seperate library of the icons in png so that i can use it for ios Apps same with android.

**Comment by scottdejonge** [comment]
The source SVGs are included in the repo. You could use a command line tool like [ImageMagick](http://www.imagemagick.org/script/index.php) to batch process the SVGs into PNGs as required, here is a [Usage Guide](http://www.imagemagick.org/Usage/basics/#convert).
